### PR TITLE
Skip slow-running proofs on CI

### PR DESCRIPTION
**Pull request by ehildenb**
Currently we are taking close to 3.5 hours on CI for the proofs, and taking quite a bit of CI resources to do so.

This removes the longest running proofs (> 900s on my machine), and decreases parallelism.

### CODE REVIEW

**Comment by radumereuta** [comment]
Do you know if this is time spent in the front end or the backend?

**Comment by ehildenb** [comment]
Mostly backend @radumereuta . Most proofs only spend up to 60s in the frontend.

**Comment by ehildenb** [comment]
Feel free to profile the tests yourself @radumereuta : https://github.com/runtimeverification/evm-semantics/issues/1165

You'll have to adjust those instructions to include the verbose information which you want, but that should be possible.

**Comment by ehildenb** [comment]
I've now disabled all that take >600s on my machine.

**Comment by radumereuta** [comment]
Can I still run them with `$ make test-prove`? I would like to still be able to test the front end with them.

**Comment by ehildenb** [comment]
Only if you delete them from `tests/slow.haskell` and `tests/failing-symbolic.haskell`

**Review by gtrepta — APPROVED** [review]

**Pull request merged**
