### PR TITLE
Finalize migration of tests/foundry

### PR DESCRIPTION
**Pull request by iFrostizz**
Related to: https://github.com/runtimeverification/evm-semantics/pull/1904
We completely remove `tests/foundry`

### CODE REVIEW

**Comment by iFrostizz** [comment]
- Made sure that the test utilities (Python, Docker) were pointing to the new location
- Bumped and pined `forge-std` to the latest release, the one that was used was ~1 year old

**Comment by palinatolmach** [comment]
@ehildenb @nwatson22 this PR seems to remove `tests/foundry` that are not used by the CI — is it something we want to do? I'll update expected output in this case. We've talked about removing it with @nwatson22 just yesterday — these tests are not used in CI and sometimes are not being updated consistently with the integration tests in `kevm_pyk`, so it makes sense to me. 

This PR also bumps the version of `forge-std` being used, so I suspect it will require updating tests and relevant rules that rely on hardcoded program counter (the loop invariant defined in [lemmas.k ](https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/tests/integration/test-data/lemmas.k) for `LoopsTest.sum_N`, in particular): 
```
- FORGE_STD_REF: Final = '27e14b7'
+ FORGE_STD_REF: Final = '75f1746'
```

**Comment by ehildenb** [comment]
Yeah, the actual test-suite has moved to a subdirectory of `kevm-pyk/...`.

**Comment by nwatson22** [comment]
I'm migrating this PR to https://github.com/runtimeverification/kontrol/

**Comment by palinatolmach** [comment]
Closed by https://github.com/runtimeverification/kontrol/pull/48.

**Pull request closed without merging**
