### PR TITLE
Add `kevm section-edge ...` command, shorten `prune-proof => prune`

### PR DESCRIPTION
**Pull request by ehildenb**
This makes some minor CLI adjustments:

- Adds the `kevm section-edge ...` command, analogue of `kontrol section-edge ...`, which allows breaking a given edge into many steps.
- Renames `kevm prune-proof ...` to `kevm prune ...`, for easier use when pruning KCFGs.

### CODE REVIEW

**Comment by yale-vinson** [comment]
@ehildenb Can you please provide a little context for this one so that we can prioritize it in tomorrow's Kontrol standup?

**Comment by ehildenb** [comment]
I was working on some of teh KEVM proofs (which are basic kclaim style ones, not Kontrol property test proofs), and needed these functionalities to help debug them. So I ported them from the Kontrol codebase here.

This isn't really directly related to or affecting kontrol, but I figured since it was useful for debugging KEVM test-suite I was working on, should get it merged, and there isn't a more appropriate board to put it on.

**Comment by yale-vinson** [comment]
@ehildenb I am working on the Kontrol board to keep things moving, and I wanted to check in on a few that you have open and in progress. Are you still working on this, or can we backlog or close it? Is this something someone else can do to take it off your plate?

**Comment by anvacaru** [comment]
I brought this up to date. I'd say we can merge it.

**Review by anvacaru — APPROVED** [review]

**Pull request merged**
