### PR TITLE
Fixed typo on foundry.md

### PR DESCRIPTION
**Pull request by lucasmt**
`AssertTest.test_assert_true` to `AssumeTest.test_assume_true`

### CODE REVIEW

**Comment by ehildenb** [comment]
Why this change? Both tests exist, so they shuold both be fine for the test.

**Comment by lucasmt** [comment]
> Why this change? Both tests exist, so they shuold both be fine for the test.

Do they? I only see `AssumeTest` here: https://github.com/runtimeverification/evm-semantics/tree/master/tests/foundry/test

**Comment by ehildenb** [comment]
The AssertTest are here: https://github.com/runtimeverification/evm-semantics/blob/master/tests/foundry/test/Simple.t.sol

The selector slug `--test ...` lets you specify ContractName.test_name, not FileName.test_name.

**Comment by lucasmt** [comment]
You're right, my mistake

**Pull request closed without merging**
