### PR TITLE
Move Additional Workflows to Ephemeral Runners

### PR DESCRIPTION
**Pull request by F-WRunTime**
From https://github.com/runtimeverification/evm-semantics/pull/2123 Testing move to Ephemeral runners.

### CODE REVIEW

**Comment by F-WRunTime** [comment]
@tothtamas28 Would the following also benefit form using the ephemeral runners as well? 
```
  kevm-pyk-unit-tests:
    needs: kevm-pyk-code-quality-checks
    name: 'Unit Tests'
    runs-on: [self-hosted, linux, normal]
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Run unit tests'
        run: |
          make -C kevm-pyk cov-unit

  kevm-pyk-profile:
    needs: kevm-pyk-code-quality-checks
    name: 'Profiling'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: 'Install Poetry'
        uses: Gr1N/setup-poetry@v8
      - name: 'Run profiling'
        run: |
          make -C kevm-pyk profile
```

**Comment by tothtamas28** [comment]
> Would the following also benefit form using the ephemeral runners as well?

`kevm-pyk-profile` runs on a public runner, which is ephemeral. But I agree, we should move `kevm-pyk-unit-tests` to `ubutnu-latest` as well.

**Review by tothtamas28 — APPROVED** [review]

**Comment by F-WRunTime** [comment]
@tothtamas28 Running on the public runners will probably slow the tests down. We have the normal Ephemerals that should be as fast as the  normal runners. It's 3 minutes... but as long as queues aren't bad internal runners would probably better, no?

**Comment by tothtamas28** [comment]
> but as long as queues aren't bad internal runners would probably better, no?

Speed is not an issue for these jobs. So as long as GitHub-hosted runners provide sufficient quality of service, I'd go with them as we do not need to maintain those.

**Comment by tothtamas28** [comment]
Since this change there is significant delay in the `Version Bump` job, probably because now it shares `flyweight-ephemeral` runners with `Code Quality Checks`.

Data: [data.csv](https://github.com/runtimeverification/evm-semantics/files/13299076/data.csv)

image

(The delay is defined as the number of second elapsed between `createdAt` in [WorkflowRun](https://docs.github.com/en/graphql/reference/objects#workflowrun) and `startedAt` in the corresponding [CheckStep](https://docs.github.com/en/graphql/reference/objects#checkstep).)

As an example, run `7147` took 15 minutes to start:
* Run: https://github.com/runtimeverification/evm-semantics/actions/runs/6798583460/job/18483017877
* Logs: https://github.com/runtimeverification/evm-semantics/commit/1339896b471b2e1e2223a9940f3b540be1c49735/checks/18483017877/logs

```
2023-11-08T13:00:37.1618602Z Requested labels: self-hosted, linux, flyweight-ephemeral
2023-11-08T13:00:37.1618926Z Job defined at: runtimeverification/evm-semantics/.github/workflows/test-pr.yml@refs/pull/2154/merge
2023-11-08T13:00:37.1619084Z Waiting for a runner to pick up this job...
2023-11-08T13:15:36.1582865Z Job is about to start running on the runner: b6e8b521ff1d (organization)
...
```

**Pull request merged**
